# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  吹雪
subtitle: Hello World
name: 吹雪
email: hauchenglee@gmail.com
description: 本站是吹雪的技術分享博客。内容涵盖生活故事與知識分享。
keywords: hauchenglee,吹雪,生活故事,編程,Developer,Programmer,Coder,Geek,Java,
encoding: "utf-8"
favicon: favicon.ico.jpg

# Link
url: http://www.hauchenglee.com
enforce_ssl: hauchenglee.com
repository: hauchenglee/hauchenglee.github.io
github_url: https://github.com/hauchenglee
line_id: hauchenglee
line_qr_pic: line_qrcode.jpg
line_qr_url: http://www.hauchenglee.com/assets/images/line_qrcode.jpg
linkedin_url: https://www.linkedin.com/in/hauchenglee/
twitter_url: https://twitter.com/hauchenglee
pixiv_url: https://www.pixiv.net/member.php?id=18488925

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
  coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
# not use
menus:

  - href: /algorithms
    label: Algorithms
    target: _self

  - href: /open-source
    label: Source
    target: _self

  - href: /link
    label: Link
    target: _self

  - href: /about.html
    label: About
    target: _self


# Navigation. main menu list
navs:

  - href: /
    label: Home

  - href: /java
    label: Java
    target: _self
#    subnav:
#
#      - subHref: /java
#        subLabel: Java
#        target: _self
#
#      - subHref: /spring
#        subLabel: Spring
#        target: _self
#
#      - subHref: /spring-boot
#        subLabel: Spring Boot
#        target: _self
#
#      - subHref: /spring-cloud
#        subLabel: Spring Cloud
#        target: _self

  - href: /arch
    label: Arch
    target: _self

  - href: /tech
    label: Tech
    target: _self

  - href: /blog
    label: Blog
    target: _self

  - href: /archives
    label: Archives
    target: _self


# labels. my blog key words
labels:

  - href: /
    label: key word 1
    target: _self

  - href: /
    label: key word 2
    target: _blank

  - href: /
    label: key word 3
    target: _blank


# selected articles
classes:

  - href: /
    name: article a
    describe: describe a

  - href: /
    name: article b
    describe: describe b

  - href: /
    name: article c
    describe: describe c


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: hauchenglee
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: hauchenglee
  repo: blog-comments
  oauth:
    client_id:
    client_secret:
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: hauchenglee
  repo: blog-comments
  clientID:
  clientSecret:
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus: true